### ISSUE TITLE
Tutorial is not clear.

### ISSUE THREAD

**Issue by Eth030** [manuel-rw/jellyfin-discord-music-bot#109]
**Describe the bug**
ERROR [ClientService] Error [TokenInvalid]: An invalid token was provided.A clear and concise description of what the bug is.

**To Reproduce**
I followed your complete instructions, invited the newly created bot to my server.
But in the Tutorial i don't find any place mentioning which of the Tokens/secrets i need to copy so i can put it into the variable: DISCORD_CLIENT_TOKEN.

Can you please tell me which of the tokens do i need to put for DISCORD_CLIENT_TOKEN?

Kind regards
I

**Comment by manuel-rw** [comment]
Hi, the installation instructions are pretty clear about this.
Depending on your installation method, you'll have to provide this token to the application.

Check out the documentation here:
https://github.com/manuel-rw/jellyfin-discord-music-bot/wiki/%F0%9F%9A%80-Installation

The token will be a random string, that acts like a password.
Never share it with anybody!

You can obtain the token from the "Bot" page in the developer portal:
![image](https://user-images.githubusercontent.com/30572287/224550311-f4a09fc5-4f5c-4f76-8b28-5133f199db4d.png)

**Comment by manuel-rw** [comment]
Hi, were you able to set it up?

**Comment by manuel-rw** [comment]
Issue is stale, please reopen if anything is still not clear
