### ISSUE TITLE
The bot plays albums at random/in the wrong order

### ISSUE THREAD

**Issue by Josemito** [manuel-rw/jellyfin-discord-music-bot#136]
**Describe the bug**
When using the bot in a Discord voice channel and trying to play an entire album, the bot adds all the tracks from the album to the playlist but doesn't play them in order.

**To Reproduce**
1. Go to the discord server your bot is on.
2. Use the command "/play" and using the autocomplete feature look for an album in your library and select it
3. Hit enter so the bot receives the command

**Expected behavior**
The album should play the tracks in order since most albums are usually played that way.

Thanks for the awesome bot🥇

**Comment by manuel-rw** [comment]
For some reason, the Jellyfin ``search-api`` returns tracks in an album in reverse. Since there seems to be no option for this, I reverse items in albums before adding them to the queue.
