### ISSUE TITLE
ADD imgur metadata scrapping

### ISSUE THREAD

**Issue by Pickymarker** [manuel-rw/jellyfin-discord-music-bot#174]
add imgur metadata scrapping to use metadata from imgur like this does https://github.com/Radiicall/jellyfin-rpc

**Comment by manuel-rw** [comment]
Hello,
your issue description is too short.
Please explain how this should be implemented and what solution you would like to have.
I do not know what metadata you want :) You need to explain that here...

**Comment by Pickymarker** [comment]
this is a feature request not a issue and if you look at that GitHub you can see what I'm talking about with the imgur metadata image scraping.

**Comment by manuel-rw** [comment]
Thanks for the reply.

1. On GitHub, all "feature requests" and "bugs" are treated as issues. Issues is the general term, as you can see in the navigation bar on top of this issue. With "issue", I was referring to your post here.
2. This is a very bad way of telling people what you want. I do know know this application, nor do I have the time to read through the entire source code of it. I appreciate your request, but it simply doesn't provide me the information I need to work on this. Even if I can figure out, how and why they scrape Igmur, I cannot know how this should be implemented in this discord bot (unless it's trivial - which it's not).

Herby, I am closing your issue. You may re-open, if you updated your description and explain in detail, what you want.
I hope you understand.

~Greetings
