### ISSUE TITLE
[JellyfinService] AxiosError: Request failed with status code 404 error 

### ISSUE THREAD

**Issue by Pickymarker** [manuel-rw/jellyfin-discord-music-bot#175]
i get this error when trying to run the non docker version on windows 
![image](https://user-images.githubusercontent.com/74084396/235358700-6f5f68b4-940f-4116-b4af-a9d975295402.png)

**Comment by manuel-rw** [comment]
Hello, you selected the wrong intents while configuring your bot.
Ensure that your bot has the correct gateway intents.

**Comment by Pickymarker** [comment]
these are the intents i'm using 
![image](https://user-images.githubusercontent.com/74084396/235361717-96e6e053-0162-464b-8f6a-8ca1c9202de5.png)

**Comment by Pickymarker** [comment]
and after enabling those i get this error 
![image](https://user-images.githubusercontent.com/74084396/235361787-5fdbb4d9-b9b9-405e-83ff-4bb630e840c9.png)

**Comment by Pickymarker** [comment]
bot works on discord but none of the jellyfin stuff or commands work

**Comment by Pickymarker** [comment]
does anyone know a fix

**Comment by manuel-rw** [comment]
Make sure, that your ``JELLYFIN_SERVER_ADDRESS`` has no trailing ``/``.

Examples, that work:
- http://x.x.x.x:8096
- http://my-jellyfin.local:8096
- https://jellyfin.domain.com:8096

Examples, that **won't work**:
- http://x.x.x.x:8096/
- http://my-jellyfin.local:8096/web/index.html
- https://jellyfin.domain.com:8096

**Comment by wes-hawkins** [comment]
I had this exact same problem, and removing the trailing / solved it. I would recommend putting an 'example' JELLYFIN_SERVER_ADDRESS in the docker container setup.

**Comment by manuel-rw** [comment]
Makes sense, I will do that and then close this issue.
