### ISSUE TITLE
Bot Cannot Play Playlist

### ISSUE THREAD

**Issue by wes-hawkins** [manuel-rw/jellyfin-discord-music-bot#182]
**Describe the bug**
My bot is up and running and can play individual tracks, but cannot play a folder/playlist/directory, even though it shows up in the /play 'matching options.'

**To Reproduce**
1. Have a sub-directory or playlist of music in your Jellyfin library.
2. Begin the /play command, and select the directory or playlist.
3. Submit the command.
4. The bot seems to queue the directory/playlist, but it does not play.

**Expected behavior**
I would expect the bot to play the contents of the directory or playlist.

**Screenshots**
![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/a8ae11fd-6eb1-4f0a-bd7b-ac790d947fc9)
![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/b0d2ffdd-650e-4c1e-b4af-3ff00fbb9f8e)
![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/079cd0e9-a2d5-4823-8dcf-3581ffe1e3af)

**Additional context**
- The bot seems to understand that the directory/playlist has a large amount of music, indicating "1 day 8 hours 47 minutes 42 seconds" of music.

Thank you!

**Comment by manuel-rw** [comment]
Hello, thanks for your feature request.
I usually dump my music into artists directories and haven't experimented yet too much with Jellyfin's capabilities.

I have verified that the following content plays:
- Single tracks
- Albums
- Playlists

Most likely, something is not working or converting the data properly for your directory.
Can you provide reproduction steps for also creating a directory, that I can use to test?

Since this is not critical, I will sadly not prioritise this issue - I hope you understand.

**Comment by wes-hawkins** [comment]
The two ways I have attempted to create a directory:

**Simply making a directory using Microsoft SMB:**
1. Navigate to my Jellyfin music directory using Windows File Explorer.
2. Create a new folder.
3. Put a handful of music files in that folder.
4. Scan library through Jellyfin WebUI.
5. Attempt to load the playlist through the Discord bot using the /play command.
6. The bot will find the folder, but will not actually play it when the command is submitted.

**Create a playlist in Jellyfin:**
1. Navigate to a music track in the Jellyfin WebUI.
2. Hit the ... menu for the track.
3. Select 'Add to Playlist'
4. Create a New playlist, give it a name.
5. Attempt to load the playlist through the Discord bot using the /play command.
6. The bot will find the playlist, but will not actually play it when the command is submitted.

**Comment by wes-hawkins** [comment]
Certainly an odd thing is that it says "Added 1 tracks to your playlist" when I try to add an entire folder/playlist... I would expect it to add all of the songs, or identify that it's a playlist instead of a track.
![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/a2cca305-f13a-407f-bd98-0ed7502113b1)

**Comment by wes-hawkins** [comment]
This is all the information I get from the log between starting the docker/bot, summoning it in Discord, and attempting to play a playlist. The UserDataChanged warning comes as soon as I attempt to play the playlist.

![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/65abc39e-05bd-4a1c-994b-aee4e19048f3)

Another odd thing is that if I try to play the same playlist repeatedly, it indicates "Added # tracks to your playlist..." incrementing by 1 each time (except for the second '3', which seems like it failed somehow.)

![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/5ad78122-d425-43f3-9270-bd55aac3e108)

**Comment by manuel-rw** [comment]
Ok, many thanks for this detailed information.
Are directories created via SMB / file system equal to the playlists?
If yes, it might just be the case that something with playlists is not working.

**Comment by wes-hawkins** [comment]
No problem, thank you! No, they are not equal--the Jellyfin playlists are saved in Jellyfin/config/data/playlists/, vs. the file system directories which are just folders full of raw files. 

In the picture below:
- 🎶 **Old School DnB** is a file system folder.
- 🎧 **DnB** is a Jellyfin playlist.

I can submit the command to play either, but the bot doesn't play. I can select and play individual songs just fine, including with the /random command.

![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/754cdf65-1a5d-4eda-94aa-8c7209335748)

**Comment by wes-hawkins** [comment]
Strangely, the music bot's icon has a green border after trying to play a playlist, as though it is playing music, but there is no audio coming through.

![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/9c293954-6923-440e-a1da-159a2298a139)

**Comment by manuel-rw** [comment]
That's weird, because if the audio cannot be loaded, no green ring will appear.
If there's a ring, it's actually streaming something.

Can you maybe enable debug using the environment variable?
``LOG_LEVEL=DEBUG``

**Comment by wes-hawkins** [comment]
More clues... looking at the Jellyfin dashboard, when I try to play a Jellyfin playlist, the bot starts--and then immediately 'finishes'--the playlist, within a split second.

![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/1747fcf4-cd21-4f8d-a219-29c3848c5471)

This is different from when I try to play a directory. The bot seems to be playing the folder, but the time displayed on the 'Active Devices' flickers between 0 and 1 second, as though the bot is continuously trying to restart the playlist.

![image](https://github.com/manuel-rw/jellyfin-discord-music-bot/assets/8751797/2e1808c4-393f-4ecc-9d72-e6afd642cdb5)

**Comment by wes-hawkins** [comment]
When trying to play a playlist:
```
[Nest] 28  - 05/14/2023, 2:32:50 AM   DEBUG [PlayItemCommand] Initiating auto-complete search for query 'dnb' with type 'undefined'
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [JellyfinWebSocketService] Opening WebSocket with client id jellyfin-discord-bot...
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [PlayItemCommand] Extracted 1 tracks from the search item
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [PlayItemCommand] Adding 1 tracks with a duration of 118062946.7136 ticks
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [JellyinPlaystateService] Reporting playback start on track 'a6d593c16efd48d4915d5ace1ca4a71a'
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [JellyfinStreamBuilderService] Building stream for 'a6d593c16efd48d4915d5ace1ca4a71a' with bitrate 96000
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [DiscordVoiceService] Playing audio resource with volume [object Object]
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [DiscordVoiceService] Initialized new instance of AudioPlayer because it has not been defined yet
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [DiscordVoiceService] Audio player changed state from idle to buffering
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [DiscordVoiceService] Audio player changed state from buffering to playing
[Nest] 28  - 05/14/2023, 2:32:55 AM   DEBUG [JellyfinWebSocketService] Received a ForceKeepAlive package from the server
[Nest] 28  - 05/14/2023, 2:32:56 AM   DEBUG [DiscordVoiceService] Audio player changed state from playing to idle
[Nest] 28  - 05/14/2023, 2:32:56 AM   DEBUG [DiscordVoiceService] Audio player finished playing old resource
[Nest] 28  - 05/14/2023, 2:32:56 AM   DEBUG [JellyinPlaystateService] Reporting playback finish on track 'a6d593c16efd48d4915d5ace1ca4a71a'
[Nest] 28  - 05/14/2023, 2:32:56 AM   DEBUG [DiscordVoiceService] Playlist has next track: no
[Nest] 28  - 05/14/2023, 2:32:56 AM   DEBUG [DiscordVoiceService] Reached the end of the playlist
```

Attempt with a directory:
```
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [PlayItemCommand] Extracted 1 tracks from the search item
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [PlayItemCommand] Adding 1 tracks with a duration of 118062946.7136 ticks
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [JellyinPlaystateService] Reporting playback start on track '7be032fc6279953912f84cd9edd170a6'
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [JellyfinStreamBuilderService] Building stream for '7be032fc6279953912f84cd9edd170a6' with bitrate 96000
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Playing audio resource with volume [object Object]
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Audio player changed state from idle to buffering
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Audio player changed state from buffering to playing
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Audio player changed state from playing to idle
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Audio player finished playing old resource
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [JellyinPlaystateService] Reporting playback finish on track '7be032fc6279953912f84cd9edd170a6'
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Playlist has next track: no
[Nest] 28  - 05/14/2023, 2:35:15 AM   DEBUG [DiscordVoiceService] Reached the end of the playlist
```

**Comment by wes-hawkins** [comment]
When I load an album/playlist, it says "Adding 1 tracks with a duration of..." and the tick duration is correct to the duration of the album/playlist. I'm not sure if it should instead be finding multiple tracks, or treating the whole album as a single 'track.'

Either way, it is strange that it immediately goes from idle -> buffering -> playing -> idle -> finished!

**Comment by s01itude** [comment]
I'm having a similar/the same issue trying to play albums. I've also noticed that once this issues happens the bot just totally craps the bed, while it responds to commands it never actually plays anything else and each request just moves the tally up a count, and the container must be restarted for it to recover.

When I go into jellyfin and connect to the bot remotely it indeed shows up as if it's playing a track, but it just plays 1 second and restarts and does that over and over. 

From my observation of it's behavior (I haven't looked at any of the logs), it sure seems like it's trying to play albums/playlists as if they are a singular audio file rather then creating a queue of the individual items.

**Comment by manuel-rw** [comment]
> opusscript_native._free is not a function

Weird. That is probably something from the Discord.js library - but I can't confirm, since there isn't much information on this.

> like it's trying to play albums/playlists as if they are a singular audio file rather then creating a queue of the individual items

That's normal behavior and indeed how the bot works :)

**Comment by sssionek** [comment]
I encountered the same bug, tracked it down to the `/play` commands handler - `handler()` in play.comands.ts
It seems that any result from the JellyfinSearchService is saved as a SearchHint, therefore when `item.toTracks()` is triggered - every album/playlist is treated like a regular track - hence the error. 
Been trying to fix it, but no luck so far - I don't really know Typescript :D
