### ISSUE TITLE
[Request]: Add pages for playlist and search results

### ISSUE THREAD

**Issue by 7kayoh** [manuel-rw/jellyfin-discord-music-bot#56]
**Is your feature request related to a problem? Please describe.**
Yes at some point, user can not view all returned search result/playlist because of the characters limit for messages in Discord.

**Describe the solution you'd like**
Use a page system so it could display all items in the playlist or play command. The bot should present buttons under the rich embed, allowing user to turn to the next or previous page by clicking on the corresponding button. In addition, a cancel button should be provided to cancel a search for the `play` command.

**Comment by manuel-rw** [comment]
Implemented in #106
