### ISSUE TITLE
[Bug]: Bot crashes when the stop command is ran and there is no track playing

### ISSUE THREAD

**Issue by 7kayoh** [manuel-rw/jellyfin-discord-music-bot#57]
**Describe the bug**
If there is no active track playing by the bot and the stop command was ran. The bot crashes as... well, there's no active track playing. Causing a TypeError `Cannot read properties of undefined (reading 'track')` at `/src/clients/jellyfin/jellyfin.playstate.service.js:86:37`, at `/src/commands/stop.command.js:41:34`

**To Reproduce**
1. Play a random track
2. Wait until the bot finishes playing
3. Run `/stop`

or
1. Run `/stop`

**Expected behavior**
The bot should check if there is a queue and let the user know the command failed as there is are tracks in the queue if there happens to be none.

**Comment by manuel-rw** [comment]
Hi,
thanks for the issue.
Just from looking at the code, it looks good to me.
Feel free to open a pull request and I'll review it asap.

**Comment by manuel-rw** [comment]
Done as fixed in #62 . Please open a new ticket for ``DiscordAPIError[10062]: Unknown interaction``, so we can track it separately.
