### ISSUE TITLE
Items Not Playing

### ISSUE THREAD

**Issue by AcidRain999** [manuel-rw/jellyfin-discord-music-bot#98]
Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] Avoided joining the voice channel because voice connection is already defined
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [JellyfinStreamBuilderService] Attempting to build stream resource for item 4eb53e54a5f162a984597f5f8e9c5586 with bitrate 64000
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [PlaybackService] Added the track '4eb53e54a5f162a984597f5f8e9c5586' to the current playlist
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [PlaybackService] A new track (fd282307-8b19-4d06-a41d-5d9f11b017e7) was requested and will be emmitted as an event
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] Initialized new instance of Audio Player because it has not been defined yet
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] state change:
from {"status":"idle","resource":false,"stepTimeout":false}
to {"status":"buffering","resource":true,"stepTimeout":false}
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] state change:
from {"status":"buffering","resource":true,"stepTimeout":false}
to {"status":"playing","missedFrames":0,"playbackDuration":0,"resource":true,"stepTimeout":false}
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] Deteced audio player status change from playing to idle. Has next track: no
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] Audio Player has reached the end of the playlist
[Nest] 410507  - 02/28/2023, 7:32:30 PM   DEBUG [DiscordVoiceService] state change:
from {"status":"playing","missedFrames":0,"playbackDuration":120,"resource":true,"stepTimeout":false}
to {"status":"idle","resource":false,"stepTimeout":false}
[Nest] 410507  - 02/28/2023, 7:32:30 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged

i am getting that error when anything tries to play. it seems it cant play the file but everything else works

**Comment by manuel-rw** [comment]
Hi 👋
Please fill out the template for issues :)
- What version are you running?
- Can you enable debug mode by setting ``DEBUG`` environment variable to ``true``?
- Can you try to switch to the ``dev`` image?

**Comment by manuel-rw** [comment]
Closing as stale because OP is inactive
